import Head from "next/head";
import { Inter } from "next/font/google";
import { useTranslation } from "next-i18next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { GetStaticProps } from "next";
const inter = Inter({ subsets: ["latin"] });


export const getStaticProps: GetStaticProps  = async ({ locale }) => {
  return {
    props: {
      ...(await serverSideTranslations(locale as string)),
    },
  };
}


export default function Home() {
  const { t } = useTranslation();

  return (
    <>
      <Head>
        <title>Dacade</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen bg-blue-500 text-white font-bold text-6xl flex justify-center items-center">
        <span>
          {t("nav.signup.already-exist")}
        </span>
      </main>
    </>
  );
}
